### ISSUE TITLE
Error executing script

### ISSUE THREAD

**Issue by hasandiwan** [jeroenbegyn/VLCControl#2]
VLCControl.scpt:1828:1832: script error: Expected end of line but found class name. (-2741) 

I don't know enough about Applescript to debug it, so I'll just report it.

**Comment by jeroenbegyn** [comment]
Which version of OSX are you using? I can't seem to reproduce this issue.

**Comment by hasandiwan** [comment]
It's been 5 years since this was a problem. I have long since worked around my issue. So, closing it. Thanks for your attention.
